### ISSUE TITLE
Current released version includes debug logging

### ISSUE THREAD

**Issue by ggoodman** [KFlash/seafox#11]
I was trying out the released version of seafox (`1.6.9`) and note that it appears to have shipped with lots of baked-in debug logging (via `console.log()`). I suspect that this was a mistake and wonder if a new release might be cut with those bits of logging removed.

I have a use-case where I need to perform semantic analysis in the browser and am looking for a combination of performance and bundle size. Seafox looks like a great candidate there!

**Comment by KFlash** [comment]
Hi. Where do you see this console.log? I will try to fix this soon as I get to a keyboard.

You could also look at EScaya and the custom parsing. No documentation yet (still WIP) , but it allow you to define your own AST during parsing and let you do what you want with the parsed input.

**Comment by ggoodman** [comment]
I've been following your work on escaya but don't have the know-how or bandwidth to understand how I could use a custom AST. Right now, I find that having an estree-compatible AST is easier to work with given that there are existing type definitions for different node types.

**Comment by ggoodman** [comment]
You can see the `console.log` statements by grepping in https://cdn.jsdelivr.net/npm/seafox@1.6.9/dist/seafox.esm.min.js.

**Comment by KFlash** [comment]
I will try to see if I find `console.log` in the source.

A custom node could be like this if you only need the string values

```js
// Global
const names = [];

// Parser option
StringLiteral: functiion(value) {
    names.push(value);
    return null; // noob
}
`
