### ISSUE TITLE
What is Seafox?

### ISSUE THREAD

**Issue by KFlash** [KFlash/seafox#2]
This is my private parser code made public. It strictly conforms to the standard ECMAScript® 2020 (ECMA-262 10th Edition) language specification, and can **not** be used as an drop-in replacement for other parsers.

The main reason for this is that all parsers uses a `parse()` method - Seafox uses either  [`parseScript`](https://tc39.github.io/ecma262/#sec-parse-script) or [`parseModule`](https://tc39.github.io/ecma262/#sec-parsemodule).

Seafox focus **only** on performance, and if you are *soft hearted* and / or can't understand super low level code - this parser isn't for you :)

I would recommend to use the [Meriyah](https://github.com/meriyah/meriyah) parser instead of Seafox if you need a parser that behave like other public parsers, and also if you are in need of performance even the fact that Seafox is 15 - 25 % faster than the mentioned parser.

**Comment by aleclarson** [comment]
Would using `/^(im|ex)port /m` to decide between `parseScript` and `parseModule` defeat the performance gain of using Seafox over Meriyah?

```ts
import { parseModule, parseScript } from 'seafox'

const moduleRE = /^(im|ex)port /m

const parse = (content: string) => 
  moduleRE.test(content) 
    ? parseModule(content) 
    : parseScript(content)
```

**Comment by nicolo-ribaudo** [comment]
That wouldn't work if you have `import` inside a string, a comment, or if you use dynamic import. For example, this is a valid script:

```js
/*
import it!
*/
` this is not an
import `
import (a).then(() => {});
```

**Comment by aleclarson** [comment]
Yeah, there are tradeoffs. But my question stands :)

**Comment by KFlash** [comment]
It shouldn't "kill" the perf, but if it's the perf you prefer and you don't are about ESTree or Babel AST, you can wait for my new CST parser.  You can test it [here](https://kataw.github.io/kataw/kataw_ast/).  **Note** most of he CST info are packed bitwise masks on the 'NodeFlags' to increase perf even more.
