### ISSUE TITLE
[Request] support onToken option like meriyah?

### ISSUE THREAD

**Issue by 3cp** [KFlash/seafox#6]

**Comment by KFlash** [comment]
@3cp I can try to support it if it doesn't kill performance. Do you want to help out?

**Comment by 3cp** [comment]
Sorry, not really :-) Unfortunately parser and TS are both out of my comfort zone :-) I had a peak on the code, probably I will cost more of your time rather than helping.

**Comment by KFlash** [comment]
I see. Meriyah is build by my students. Seafox is my private code as you can see the differences in the source. So I guess it kind of "super hard" for most people :) 

How do you want a `onToken` ? What do you expect it to do?

**Comment by 3cp** [comment]
For me, I only need a way to extract tokens, so `onToken(token)` is enough for my use case. For the moment, I will just use meriyah.

**Comment by KFlash** [comment]
I started to look into it. Can't promise any exact time when it's done

**Comment by KFlash** [comment]
@3cp You can track my progress [here](https://github.com/KFlash/seafox/commit/8bcd679fd00f84e8cc7c8f60ab2ef61364a26cc6). This implementation will be different than in Meriya because I maintain the speed, and there is a flaw in Meriyah. Some keywords can also be a identifier.

**Comment by 3cp** [comment]
Thx very much!

Another question. I guess seafox doesn't need `lexical` option, and would not implement `jsx` option (not an issue for my usage)?

**Comment by KFlash** [comment]
lexical is already build-in by default. There is no option for it. JSX isn't a JS standard, so no plans to implement it.

**Comment by KFlash** [comment]
@3cp How do you want the output?

Just now it is 

```ts
Keyword
Keyword
Identifier
Keyword
Keyword
```

I plan to do something like this

```ts
[ { type: 'Keyword', value: 'const' },
  { type: 'Identifier', value: 'answer' },
  { type: 'Punctuator', value: '=' },
  { type: 'Numeric', value: '42' } ]
```

Callback or array? I can't do both. It will kill performance with 1% if I do an array check

**Comment by 3cp** [comment]
I think callback like existing onToken is fine. User can still build the whole tokens array from that callback.

The whole tokens array is indeed costly for large input.

**Comment by 3cp** [comment]
I might miss-understood your question.

**Comment by 3cp** [comment]
If I turn on `loc: true`, I would expect token contains location information.

**Comment by KFlash** [comment]
Okay. I will fix that so you can do `parseScript('1/2, function() {}`)`. 

Loc information will be added. Working on the API now and performance.

**Comment by KFlash** [comment]
@3cp It's implemented, but I need to play around with it and optimize and fix edge cases. The API is different than Meriyah :)

```ts
parseScript('false', {  onToken: function(token, value, dirty, start, end) {},  loc: true  });
```

`token` - Current token
`value` - token value
`dirty` - Either true or false. True if invalid code
`start` - On if loc is enabled
`end`  - On if loc is enabled

**Comment by KFlash** [comment]
Almost done! Here is a few test cases. 

https://github.com/KFlash/seafox/blob/ontoken/test/parser/miscellaneous/onToken.ts#L38

**Comment by KFlash** [comment]
@3cp It have landed on Master branch, but still I need to work on it to improve it, and also fix the edge cases before I push a new version to NPM. It's different than Meriyah implementation.

It does tokenization super fast, and the performance is still the same. No perf loss :)

The API is 

`parseScript('false', {  onToken: function(token, value, start, end) {},  loc: true  });`

Not that if you parse invalid JS code, it will throw the normal way and will not give you any tokens to collect.

I'm closing this now as solved. Still need to improve it, but you can use the Master branch for now.

**Comment by 3cp** [comment]
Thx!

**Comment by KFlash** [comment]
Read this https://github.com/KFlash/seafox/blob/master/README.md#lexical-analysis
