### ISSUE TITLE
Reused bit in common flags bit set

### ISSUE THREAD

**Issue by migueloller** [KFlash/seafox#7]
I was browsing the source code and stumbled across a bit set that had a duplicate bit set ("set" being the verb here). Is this intentional?

https://github.com/KFlash/seafox/blob/d5242d0bb46ec202d4614e0a7e1a09b5b82b7bba/src/parser/common.ts#L58-L59

**Comment by KFlash** [comment]
This wasn't intentional, and just a stupid slip-up! Thanks for noticing this.
