### ISSUE TITLE
Confused about the AST related to optional chaining expressions

### ISSUE THREAD

**Issue by axefrog** [KFlash/seafox#9]
The following two expressions produce unexpectedly different output structures. I'm confused why this might be the case, and (assuming it's not a bug) how I should logically understand the structure when it comes to rendering. It's not clear, based on the AST, exactly where the optional chain operator should go. Why is `c` optional in the second example but not the first? Why does a computed property affect the structure so much? Also why is there always a `base` property? Why not just an array of chaining members?

Note that I'm trying this with Seafox as I was previously trying to do it with Meriyah, but Meriyah was producing an even more confusing structure with a kind of weird backward-nested structure that seems to chain in reverse via nested `base` properties.

```
seafox.parse(`a?.b?.[c]`)
seafox.parse(`a?.b?.c`)
```

Relevant outputs:

```json
{
  "type": "MemberExpression",
  "object": {
    "type": "ChainingExpression",
    "base": {
      "type": "Identifier",
      "name": "a"
    },
    "chain": [
      {
        "type": "MemberChain",
        "computed": false,
        "property": {
          "type": "Identifier",
          "name": "b"
        },
        "optional": true
      }
    ]
  },
  "computed": true,
  "property": {
    "type": "Identifier",
    "name": "c"
  }
}
```

```json
{
  "type": "ChainingExpression",
  "base": {
    "type": "Identifier",
    "name": "a"
  },
  "chain": [
    {
      "type": "MemberChain",
      "computed": false,
      "property": {
        "type": "Identifier",
        "name": "b"
      },
      "optional": true
    },
    {
      "type": "MemberChain",
      "computed": false,
      "property": {
        "type": "Identifier",
        "name": "c"
      },
      "optional": true
    }
  ]
}
```

**Comment by axefrog** [comment]
For reference, Meriyah is doing this:

```
a?.b?.[c].d
```

```json
{
  "type": "OptionalExpression",
  "object": {
    "type": "OptionalExpression",
    "object": {
      "type": "Identifier",
      "name": "a"
    },
    "chain": {
      "type": "OptionalChain",
      "base": null,
      "computed": false,
      "property": {
        "type": "Identifier",
        "name": "b"
      }
    }
  },
  "chain": {
    "type": "OptionalChain",
    "base": {
      "type": "OptionalChain",
      "base": null,
      "computed": true,
      "property": {
        "type": "Identifier",
        "name": "c"
      }
    },
    "computed": false,
    "property": {
      "type": "Identifier",
      "name": "d"
    }
  }
}
```

**Comment by KFlash** [comment]
@axefrog I agree this was confusing, but Meriyah's implementation was based on of ESTree's first attempts to implement this, and Seafox implementation was baded on ESTree's latest implementation.

Now ESTree have settled on this, but Seafox nor Meriyah have been updated to catch up with ESTree mainbly because I have been to busy and Meriyah is a student project.

If it help I think ESTree's finaly AST would be similar to what you see below. **Note** The AST example is from my own AST - **not** ESTree

```ts
// a?.b?.c

{
    "type": "Script",
    "directives": [],
    "leafs": [
        {
            "type": "ExpressionStatement",
            "expression": {
                "type": "OptionalExpression",
                "member": {
                    "type": "OptionalExpression",
                    "member": {
                        "type": "IdentifierReference",
                        "name": "a"
                    },
                    "chain": {
                        "type": "MemberChain",
                        "chain": null,
                        "property": {
                            "type": "IdentifierName",
                            "name": "b"
                        },
                        "computed": false
                    }
                },
                "chain": {
                    "type": "MemberChain",
                    "chain": null,
                    "property": {
                        "type": "IdentifierName",
                        "name": "c"
                    },
                    "computed": false
                }
            }
        }
    ],
    "webCompat": true
}


// a?.b?.[c]

{
    "type": "Script",
    "directives": [],
    "leafs": [
        {
            "type": "ExpressionStatement",
            "expression": {
                "type": "OptionalExpression",
                "member": {
                    "type": "OptionalExpression",
                    "member": {
                        "type": "IdentifierReference",
                        "name": "a"
                    },
                    "chain": {
                        "type": "MemberChain",
                        "chain": null,
                        "property": {
                            "type": "IdentifierName",
                            "name": "b"
                        },
                        "computed": false
                    }
                },
                "chain": {
                    "type": "MemberChain",
                    "chain": null,
                    "property": {
                        "type": "IdentifierReference",
                        "name": "c"
                    },
                    "computed": true
                }
            }
        }
    ],
    "webCompat": true
}


```

**Comment by KFlash** [comment]
I will try to update this in Seafox soon as I get time :)

**Comment by axefrog** [comment]
Ok, no worries, and thanks :)

I have no preference for what AST you use, as my code does not need to conform to any public conventions or standards. Just trying to make my renderer generate correct output. Currently I'm losing chunks and getting JavaScript errors because the logic I'm supposed to follow is unclear.

**Comment by axefrog** [comment]
Your output for `a?.b?.[c]` ... did you manually type this, or is it from an unpublished version of Seafox? I ask because my output does not include `c` in the optional chaining subtree.

**Comment by KFlash** [comment]
`a?.b?.[c].` was generated by Escaya. An parser that does error recovery and incremental parsing  An "work in progress" I'm soon going to open source. It also do "normal" parsing as in Meriyah and Seafox.

**Comment by axefrog** [comment]
Ah, well I'll definitely be interested in hearing more about Escaya when you're ready to talk about it!

**Comment by KFlash** [comment]
Maybe I'm soon ready to open source. Anyway. This IS Escaya :)

![escaya](https://user-images.githubusercontent.com/31855118/85387247-2a155c00-b577-11ea-8adc-3b0131cb348b.png)

**Comment by KFlash** [comment]
@axefrog You can read about Escaya in it's offical repo found [here](https://github.com/escaya/escaya).

Escaya AST is located [here](https://github.com/escaya/escaya/blob/master/src/types.ts)

**Comment by KFlash** [comment]
A Escaya live demo is up and running now. https://escaya.github.io/escaya/

**Comment by axefrog** [comment]
Ooh, that looks really useful! In fact, the system I've been designing all this time could definitely use something like this for the user/developer-facing side of things. I've been thinking for a while about an upcoming requirement I'll have where code is being edited and converted into an AST as you type. The entire system's runtime is reactive with a kind of fractal self-recompiling architecture. If I edit the contents of a script - maybe inserting a line of code, editing a function's name, etc., then ideally I want to recompile the minimum subset of runtime artifacts possible and merge them into runtime state, replacing only the functions and so forth that have actually changed. Having a stable AST that is designed to change per keystroke is perfect for this, as otherwise diffing is required, which brings with it all kinds of headaches like trying to work out stuff like whether a block of code was moved, modified or replaced, or if the function being renamed is actually a new function or just an update to an existing one. etc. Will keep tabs for sure.

**Comment by KFlash** [comment]
It will change per keystroke in that way it walk the previous AST and look for changes. If no changes the AST node or an array of AST nodes will just be returned to you from the old tree. No parsing needed! And the headache you mentioned is something you can't avoid, but Escaya does it behind the scene while walking the previous AST and do a quick range comparison. It will stop walking if the AST node you request isn't in the range you are in, or the node itself have been marked as dirty or in a different parsing context. If that's the case, you re-parse only the "dirty" node, and on next "update" it will be recovered if possible again from the old tree.

The logic is still work in progress, but it works :)

**Comment by KFlash** [comment]
You will never notice the incremental part of the parser if you set it up correctly, and you can't see it either 

But this is how the recovered nodes will look like

![works](https://user-images.githubusercontent.com/31855118/85519760-8d18f880-b634-11ea-9425-291bbee24246.png)

**Comment by KFlash** [comment]
@axefrog If you try out the REPL, look how the AST distinguishes between "pattern" and "assignment", and take any section of the spec and compare against the AST output ;)  This is some of the secret design goal with this AST. It took time to fix it.

In ESTree everyhting is a "pattern" or an "identifier"

**Comment by KFlash** [comment]
@axefrog The Escaya have been updated now to handle incremental parsing. Try out the demo again, click "F12" in Chrome and write a bunch of ';;;;;;' .  Now try to move the cursor in different directions or do a keystroke.

This is how it works :)

**Comment by axefrog** [comment]
Sorry for the extremely slow reply... I get so buried in my work that I sometimes forget how much time has passed. I will definitely be coming back to this probably fairly soon. My ability to delve into it properly and provide feedback is kind of predicated on certain foundations in my system working properly so that I can use them to drive the code generators that are powered by your projects. I think I'm almost there though, so I'll report back when ready.

**Comment by KFlash** [comment]
K. If you plan to use Escaya in the future you may need to study at the Typescript types for the Escaya AST first, but if you know the ECMAScript specs it shouldn't be a problem to understand the logic. It's more or less equal to the specs.
